### ISSUE TITLE
Can't open RAW, or copy payload or download payload - Docker compose

### ISSUE THREAD

**Issue by AmrouHab** [0dayCTF/reverse-shell-generator#106]
I built from latest version

this is my docker-compose : 

```YAML
version: '3'
services:
  revshells:
    image: reverse_shell_generator:latest
    container_name: revshells
    ports:
      - "7778:80"
    restart: always
    volumes:
      - /directory_for_container/:/revshells/
```

1) can't copy i get this error message 
[![https://imgur.com/6dI5b3O.png](https://imgur.com/6dI5b3Ol.png)](https://imgur.com/6dI5b3Ol.png)

2) Downloading opens new window to save then nothing happens

3) Opening in RAW isn't working either 
[![https://imgur.com/WqIUvuU.png](https://imgur.com/WqIUvuUl.png)](https://imgur.com/WqIUvuUl.png)
